### ISSUE TITLE
"jit" feature not working on "current" nightly(2018-05-19)

### ISSUE THREAD

**Issue by petoknm** [tov/bf-rs#1]
I know that it is caused by `dynasm` but maybe you could update to dynasm 0.2 if it is possible. This is an awesome brainfuck interpreter/compiler project and it would be nice to keep it alive. Thanks.

```shell
> cargo build
   Compiling stable_deref_trait v1.0.0
   Compiling bitflags v0.9.1
   Compiling memmap v0.5.2
   Compiling owning_ref v0.3.3
   Compiling dynasm v0.1.4
   Compiling dynasmrt v0.1.4
error[E0063]: missing field `edition` in initializer of `syntax::ext::base::SyntaxExtension`
  --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/dynasm-0.1.4/src/lib.rs:44:35
   |
44 |                                   SyntaxExtension::NormalTT {
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `edition`

error[E0609]: no field `identifier` on type `&syntax::ast::PathSegment`
   --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/dynasm-0.1.4/src/arch/x64/parser.rs:550:31
    |
550 |     Some(Ident {node: segment.identifier, span: path.span})
    |                               ^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors occurred: E0063, E0609.
For more information about an error, try `rustc --explain E0063`.
error: Could not compile `dynasm`.
```

**Comment by tov** [comment]
I'll look into it. Thanks for calling it awesome!

**Comment by tov** [comment]
It appears to be an incompatibility between dynasm and the current nightly. It was working for me on a two-week-old nightly, and then I just upgraded to the current nightly and it no longer builds. This is true for dynasm 0.2.0 as well.

**Comment by petoknm** [comment]
nice... could you maybe specify the exact version (date)? I really want to try the jit stuff... sounds super cool

**Comment by petoknm** [comment]
got it working on:
```
nightly-2018-04-04-x86_64-unknown-linux-gnu rustc 1.27.0-nightly (637ac17c5 2018-04-03)
```

**Comment by tov** [comment]
Yes, that version should I hope work until dynasm updates.

**Comment by tov** [comment]
I reported [an issue](https://github.com/CensoredUsername/dynasm-rs/issues/32) to dynasm and sent them [a PR](https://github.com/CensoredUsername/dynasm-rs/pull/33) that fixes the problem. So hopefully they will accept the PR and release a new version soon.
