### ISSUE TITLE
LLVM API with input output arguments

### ISSUE THREAD

**Issue by petoknm** [tov/bf-rs#2]
Hi,
I am trying out the llvm feature and I see that I can `llvm_run()` my `peephole` program but there is no API to set the input and output like with the `Interpretable` programs. Am I missing something or is that just not supported yet?
Thanks for the great work!

**Comment by tov** [comment]
It's not supported, sorry. I couldn't figure out how to get a `Read` and `Write` impl into LLVM, so it just calls the C library `getchar` and `putchar`.
